name: catfacts
namespace: catfacts
replicaCount: 1
image:
  repository: catfacts/catfacts-fastapi
  pullPolicy: Always
  tag: latest

serviceAccount:
  create: true
  name: "catfacts-svc"

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000

service:
  type: ClusterIP
  port: 80


resources:
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

labels:
  app: catfacts

hostnames:
  - catfacts.gensokyo.lan
istio:
  injection: "enabled"
  gateway: "ingressgateway"
