apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.name }}-gw
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: {{ .Values.istio.gateway | default "ingressgateway" | quote }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      {{- range $v := .Values.hostnames }}
      - {{ $v }}
      {{- end }}
