apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "http" | quote }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- include "labels" . | indent 2 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
